application: dilmefiquese
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*)\.html
  static_files: \1.html
  upload: (.*).html
  secure: always
  login: admin

- url: /(.*)\.jpeg
  static_files: \1.jpeg
  upload: (.*).jpeg

- url: /.*
  script: legendario.py
