application: legenda-me
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*)\.html
  static_files: \1.html
  upload: (.*).html
  secure: always
  login: admin

- url: /(.*)\.(jpeg|css)
  static_files: \1.\2
  upload: (.*).(jpeg|css)

- url: /.*
  script: legendario.py
